### ISSUE TITLE
Is it possible to direct crash logs to /share/zigbee2mqtt? Debug logging support?

### ISSUE THREAD

**Issue by james-fry** [danielwelch/hassio-zigbee2mqtt#10]
I noticed that when a crash occurs the log is written to a container path:

e.g. :
/root/.npm/_logs/2018-05-17T18_39_57_529Z-debug.log

When the container is restarted after the  crash the _logs dir is removed, so log is lost.
Can we re-direct crash logs to the mapped volume for persistence?

Also is there any easy way to enable debug logging per here:
https://github.com/Koenkk/zigbee2mqtt/wiki/How-to-debug
(I will see if I can hack it in for now)

**Comment by danielwelch** [comment]
I was hoping this was already the case. Looking at https://github.com/Koenkk/zigbee2mqtt/blob/c5cb60e998f6e2178e8a02bdd893860e89bd87f3/lib/util/logger.js, logs should be being dumped to the datapath. As I mentioned, I’ve been traveling since we went to the new datapath approach to configuration, so haven’t verified that the log.txt file is actually being created and written to. Do you see anything there?

> Also is there any easy way to enable debug logging per here:
https://github.com/Koenkk/zigbee2mqtt/wiki/How-to-debug
Yes, this should be easy. I’ll work on it.

**Comment by james-fry** [comment]
The main log definite is written to the data_path (as log.txt) - works great.
What I was after is the debug log on crash that is named with a timestamp:

/root/.npm/_logs/2018-05-17T18_39_57_529Z-debug.log

You can see example in my issue on zigbee2mqtt here:
https://github.com/Koenkk/zigbee2mqtt/issues/51

This is probably related, too: 
https://github.com/Koenkk/zigbee2mqtt/issues/48
