### ISSUE TITLE
Devices unavailable (and double) after restart

### ISSUE THREAD

**Issue by slackdance** [danielwelch/hassio-zigbee2mqtt#111]
Hello!

After restarting my PI, all mqtt devices has become unavailable in HA. WhenI go into Configuration -> Integrations -> MQTT, they are listed, but have changed name and appear to have a double set of variables. 

I think this came after using the "friendly_name" in Zigbee2mqtt's configuration.yaml. 

How can I revert this? Tried searching - and it seems confusing. How do I even remove a device all together? One of my dimmers stopped working, and while trying to re-pair; I ended up with a confusing mess of a non-working dimmer and identical entries in the core.device_registry.

**Comment by hawaltie** [comment]
I have exactly the same problem. All of my Zigbee devices seem to have been paired, they all send commands and information (at least that is what the logs show) but the devices are unavailable in Homeassistant. I am also not able to send mqtt messages (e.g. networkmap, join, etc.) to zigbee2mqtt. Perhaps it is just because I have not upgraded to the latest firmware (I have a broken connector cable, so I am not able to upgrade the zigbee stick).

**Comment by hawaltie** [comment]
I solved the problem by re-pairing the devices. Doing this I could also make use of the new functions of Zigbee2MQTT (network, channel etc.)
