### ISSUE TITLE
Setting up a build environment

### ISSUE THREAD

**Issue by deisi** [danielwelch/hassio-zigbee2mqtt#112]
Hey,

For my [PR](https://github.com/danielwelch/hassio-zigbee2mqtt/pull/110) I used a very dirty local build environment, where I added:

- `zigbee2mqtt-edge/requirements.txt`
- `zigbee2mqtt-edge/run.sh`
- `zigbee2mqtt-edge/set_config.py`

by copying them from `zigbee2mqtt`. I also had to edit:

- `local_build.sh`
- `zigbee2mqtt-edge/config.json`

and because all these changes are just to make local test somewhat work, I didn't commit them. So how do you test your builds prior to pushing them to git? The current structure makes contributing kind of hard I think. I would like to simplify this, but have no clear plan how to do so. Any suggestions?

**Comment by danielwelch** [comment]
Yeah, with the community hassio build environment, I think we're a little limited in local build options, particularly because we're dealing with the stable and edge subdirectories. I've just been relying on building the images in travis. I can update `.travis.yml` to build docker images (not push them) on pull requests. I'd definitely like to make things easy for contributing and local testing though.

I basically run pytest locally, will use the `local_build.sh` script for releases or for trouble-shooting docker / build issues, but other than that pretty much leave the build testing to travis, particularly for edge version.

**Comment by deisi** [comment]
>  I can update `.travis.yml` to build docker images (not push them) on pull requests.

you mean for testing or? 

Is the plan to add this to https://github.com/hassio-addons ? If so, this would mean splitting up edge and stable into to different repositorys.

**Comment by danielwelch** [comment]
> you mean for testing or?

yes, to test PRs and make sure they don't break image docker building.

> Is the plan to add this to https://github.com/hassio-addons ?
Not that I'm opposed to it, but I have no plans to do so and have never been asked or approached about it. I / we made the decision to follow the esphome model for edge vs stable versioning awhile ago.

**Comment by deisi** [comment]
**some thinking that I removed because it was just blabla **

Maybe the current structure is already all we need. How about trying to isolate stable and edge a little  more. Lets just have all the files double. New changes are supposed to be committed to edge and get tested there. You then have to make sure they work in stable by hand. Because there are not that many commits/time this should be fine.

I would suggest adding an additional Folder maybe call `local`, `testing` or `dev` that is essentially the edge version but builds the docker image on the local machine and not pulls it from docker hub. That way one can first add and test new things locally and then commit them upstream.

Sounds reasonable or too much hand work? From an automation point of view not really ideal but maybe sufficient for the project.

**Comment by danielwelch** [comment]
Initially I did have duplicate files, but it just led to errors caused by changing one file but not the other, and I think it’s just unnecessary repetition. Put another way, you’re sacrificing the dev experience of making adjustments to those duplicated files (more common) to make it easier to make sure your changes don’t break a docker build (less common and already handles in Travis). In addition, you don’t have to worry about any of those changes actually being released in stable (even though the files are in the stable subdir) because they won’t be released until a git tag is pushed. So they are tested in edge, and then when everything is confirmed working, all there is to do is add a tag.

I actually do have a third directory locally that I am using to debug a docker build issue right now, but this amplified the DRY problem above. Now there are three files that have to be changed every time you want to update one. So I haven’t and don’t plan to commit this into VCS.

I agree that it’s kind of awkward to test docker builds on edge locally right now though.

**Comment by deisi** [comment]
didn't check yet (will once I'm home), but could [ADD](https://docs.docker.com/engine/reference/builder/#add) instead of COPY be the solution? If I understand this correctly, we could ADD files from toplevel(../run.sh), or even url(github.comd/blabla) and thus have all the auxilarie files only once in the repository.

**Comment by danielwelch** [comment]
I don’t think you can ADD or COPY files outside of the build context. Furthermore, things are complicated by the fact that the community build environment itself is dockerized, and the build env config only accepts a target directory containing a Dockerfile as an argument.

**Comment by deisi** [comment]
sadly you are right :(, one could probably add a link and download stuff from web, but that again defeats the purpose of the whole thing because it then becomes difficult to develop things local again.

**Comment by deisi** [comment]
I think I'm a dead fish in the water here. I close this for now until I have a good idea.
