### ISSUE TITLE
Socat support

### ISSUE THREAD

**Issue by KennieNL** [danielwelch/hassio-zigbee2mqtt#148]
Is there a possibility to run socat in the hassio docker image?
I'm running a C2530 with ESP8266 because I run hassio within a VM so I dont have direct usb/serial access: https://www.zigbee2mqtt.io/how_tos/how_to_esp8266_with_cc2530.html

The tutorial gives socat possibilities, which work fine if I run zigbee2mqtt outside of a hassio (so just on my VM).

I think it should be possible by adding the socat package, and run a service/script before starting zigbee2mqtt?

I'm not very familiar with docker development, so I'm not sure what the way to go would be in adding this.

**Comment by danielwelch** [comment]
I'm confused. If you're running zigbee2mqtt on your esp8266, why do you also need to run it within hassio? And if you're not going to connect your C2530 to your hassio instance for the reasons you stated, then running zigbee2mqtt as an add-on isn't really an option in the first place?

**Comment by KennieNL** [comment]
No zigbee2mqtt doesn't run on the ESP8266.
The ESP8266 exposes a serialport (the C2530 in this case) over IP so something can connect to it. Using socat you can connect to it, and create a serial device that can be used.

Zigbee2mqtt doesn't have a possibility to connect to a serial device using IP, so I need to start socat first somehow.

Hope that clears it up :)

**Comment by danielwelch** [comment]
Ah, I gotcha. Thanks for the clarification. I think this is probably possible (although I have never heard of socat until now), but I don't really want to add complexity / another dependency and increase the docker image size (although, granted, by how much I don't know) for what seems like a fairly niche need. Might be better to just run zigbee2mqtt on it's own, rather than as a hassio addon?

**Comment by KennieNL** [comment]
Socat is only a few KB :)

bash-4.4# apk add socat
fetch http://dl-cdn.alpinelinux.org/alpine/v3.9/main/x86_64/APKINDEX.tar.gz
fetch http://dl-cdn.alpinelinux.org/alpine/v3.9/community/x86_64/APKINDEX.tar.gz
(1/1) Installing socat (1.7.3.2-r5)
Executing busybox-1.29.3-r10.trigger
OK: 161 MiB in 44 packages
bash-4.4# ls -hl /usr/bin/socat
-rwxr-xr-x    1 root     root      331.3K Nov 26 20:13 /usr/bin/socat

In my case I can yes, but someone with hassio on a raspberry they can't.
I think the only thing would be required to add some sort of socat section in the config and if it's configured: run a extra command on start up :)

**Comment by james-fry** [comment]
Can’t you pass the usb device through to the vm? This is what I do (VMware esxi)

**Comment by jannekayra** [comment]
It's not possible to pass through the USB device because the USB device is connected to another machine (ESP8266 or something else. A Raspberry pi in my case.)

I've been looking for a solution for the past a couple of months but these is no solution at the moment.

In my case, the C2530 is in another building: An ESXi Server running HassOS/Hass.io as a VM is running in the garage and C2530 will be connected to a Rasberry Pi in the main building. I would prefer to run just ser2net on the Raspberry Pi with a read only filesystem and everything else on the HassOs VM.

The only thing stopping me is that I'm unable to run socat on Hass.io.

There's even exists a Docker image for this s it's not a niche need: [https://hub.docker.com/r/forepe/zigbee2mqtt-socat](url)

Would it be possibe to develop a socat add-on for Hass.io?

**Comment by james-fry** [comment]
Ah, got you.
If you run hassio on e.g. Ubuntu rather than hassos then you can run socat on the ubuntu OS and zigbee2mqtt (or other) hassio addons can use that use device.

**Comment by jannekayra** [comment]
Yes I know :) but I'd really like to use the official HassOS image. Will try to allocate some time to investigate the possiblity of a socat addon. Anyone has any hints. Please let me know!

**Comment by KennieNL** [comment]
You mean like a general socat addon? I don't think thats possible since socat will create a tty device in /dev that will only be accessable from the specific container. The file itself is just a symlink.

I do think the zigbee2mqtt-socat has a nice way to run socat and zigbee2mqtt... see the github page: https://github.com/peterforeman/homeassistant-socat

That for hassio is what I'm looking for :)

**Comment by danielwelch** [comment]
https://hub.docker.com/r/alpine/
Considering the use cases outlined here, would it be possible to make the symlink available somewhere where another add-on has read access? Just thinking out loud... I’m not familiar with socat

**Comment by KennieNL** [comment]
I tried that but the problem is the location of the symlink would not be accessable
E.g. i would create start socat using /config/serialport-zigbee in the commandline, it would create a symlink to /dev/pts/0:
lrwxrwxrwx   1 zigbee2mqtt zigbee2mqtt   10 May 20 18:54 serialport-zigbee2mqtt -> /dev/pts/0

/config is shared between docker containers, but when trying to access the symlink it would try to access /dev/pts/0, in its own container.

The best way to implement this is by looking at how it's done in these two implementations:
https://github.com/peterforeman/homeassistant-socat
https://www.github.com/vladbabii/homeassistant-socat

This way socat would run in the same container as zigbee2mqtt would and work just fine :)

**Comment by james-fry** [comment]
If you are able, why not fork the zigbee2mqtt addon and add to the dockerfile the scoat/runwatch shell stuff from the dockerfiles from the other repos you linked
https://github.com/peterforeman/homeassistant-socat/blob/master/Dockerfile
https://github.com/vladbabii/homeassistant-socat/blob/master/Dockerfile

Or do what these other repos do and start with the zigbee2mqtt docker image as the start point.

**Comment by danielwelch** [comment]
I agree. I’d suggest making your own add-on that runs these together.

**Comment by donnib** [comment]
@KennieNL I am interested in the same thing. I will search to see if i can find a solution, it would be a shame to have to make a special container for this because then you have to handle the upgrade yourself.

**Comment by vevsvevs** [comment]
@danielwelch it would be absolutely awesome feature using TCP-socket as a serial device. In my case, i have HassOS VM over Hyper-V which lacks the ability of USB/Serial devices passthrough, and also i can't modify the guest system (HassOS not intended for this). Using VirtualBox is not an option, because it has some serious connectivity issues with heavy-loaded bridged adapters. Using HassIO over regular OS also not an option, because it breaks the easy-to-deploy concept of Hass and has noticeable bigger memory consumption (in which i limited). Incorporating socat with Zigbee2Mqtt would solve all these problems, and as i know, Hyper-V + HassOS is not so rare use case. Please consider for making this improvement for your add-on :)

**Comment by EssentialNRG** [comment]
Added socat support in PR #239
