### ISSUE TITLE
How to upgrade the add-on to latest dev branch? Version should increment...

### ISSUE THREAD

**Issue by carldebilly** [danielwelch/hassio-zigbee2mqtt#257]
Once the "edge" version is installed, there's no way to "upgrade" to latest version because the version number never changes.

I need to install and reinstall it to force been on latest `dev` channel version. It should be easier.

**Comment by carldebilly** [comment]
#258 is related.

**Comment by Sabuto** [comment]
the problem with this is that this addon is an extension of zigbee2mqtt therefore as a release of zigbee2mqtt is released then this has to be updated to work so it won't necessarily coincide with the branch also i've just looked at the edge dockerfile and this is pulled in when the dockerfile is built so there is not an easy way to do this.

**Comment by carldebilly** [comment]
That's why I opened this issue last week: https://github.com/Koenkk/zigbee2mqtt/issues/2263

**Comment by danielwelch** [comment]
I agree, it’d be nice to be able to upgrade rather than reinstall. As you probably know, a docker image is built and pushed with each commit to the dev branch. The new versioning scheme in the linked issue doesn’t really solve the problem of having a “unique” version for each commit. I think, for Hassio to realize an update is available, the config.json needs to be updated for each new version, which would mean that needs to be updated for every commit to the dev branch to something unique.
