### ISSUE TITLE
Aqara Opple Switch (WXCJKG13LM) problem

### ISSUE THREAD

**Issue by jacekpaszkowski** [danielwelch/hassio-zigbee2mqtt#290]
**zigbee2mqtt add-on version (if edge, please report commit hash):**
version 1.9.0-dev (commit #cf1bb386ead98a78b6b3bfed01e8d151cc7e9c6c) and version 1.9.0 stable

**Operating environment (HassOS, Virtual Machine, Device/platform running Hass.io):**
Raspberry Pi3 Hass.io

**Description of problem:**
I'm not able to get fully working my Aqara Opple Switch (WXCJKG13LM). For some button there is only single click, some also has hold/relese, none has double click.

- button 1: only single click (doble click reported as single)
- button 2: only single click (doble click reported as single)
- button 3-4: only single click (doble click reported as single), hold/release works ok

Second question is that each restart addon seems to loose all the data. I have to pair and unpair devices after each addon restart.
EDIT: i've manged to get it working

**Your entire configuration from the frontend (with sensitive fields redacted)**:
```json
{
  "data_path": "/share/zigbee2mqtt",
  "devices": "devices.yaml",
  "groups": "groups.yaml",
  "homeassistant": false,
  "permit_join": true,
  "mqtt": {
    "base_topic": "zigbee2mqtt",
    "server": "",
    "user": "",
    "password": ""
  },
  "serial": {
    "port": "/dev/serial/by-id/usb-Texas_Instruments_TI_CC2531_USB_CDC___0X00124B0018DE81C2-if00"
  },
  "advanced": {
    "pan_id": 6754,
    "channel": 11,
    "network_key": [
      1,
      3,
      5,
      7,
      9,
      11,
      13,
      15,
      0,
      2,
      4,
      6,
      8,
      10,
      12,
      13
    ],
    "availability_blacklist": []
  },
  "ban": [],
  "whitelist": [],
  "queue": {},
  "socat": {
    "enabled": false,
    "master": "pty,raw,echo=0,link=/dev/ttyZ2M,mode=777",
    "slave": "tcp-listen:8485,keepalive,nodelay,reuseaddr,keepidle=1,keepintvl=1,keepcnt=5",
    "restartdelay": 1.0,
    "initialdelay": 1.0,
    "options": "-d -d",
    "log": false
  }
```

**Your logs from Hass.io**
```
zigbee2mqtt:info  2020-01-27 22:59:09: Device '0x04cf8cdf3c75b85a' is supported, identified as: Xiaomi Aqara Opple switch 3 bands (WXCJKG13LM)
zigbee2mqtt:info  2020-01-27 22:59:09: MQTT publish: topic 'zigbee2mqtt/bridge/log', payload '{"type":"pairing","message":"interview_successful","meta":{"friendly_name":"0x04cf8cdf3c75b85a","model":"WXCJKG13LM","vendor":"Xiaomi","description":"Aqara Opple switch 3 bands","supported":true}}'
zigbee2mqtt:info  2020-01-27 22:59:09: Configuring '0x04cf8cdf3c75b85a'
zigbee2mqtt:info  2020-01-27 22:59:14: Successfully configured '0x04cf8cdf3c75b85a'
zigbee2mqtt:info  2020-01-27 22:59:21: MQTT publish: topic 'zigbee2mqtt/0x04cf8cdf3c75b85a', payload '{"linkquality":23,"battery":"100.00","voltage":3000}'
zigbee2mqtt:info  2020-01-27 22:59:21: MQTT publish: topic 'zigbee2mqtt/0x04cf8cdf3c75b85a', payload '{"linkquality":21,"battery":"100.00","voltage":3000,"action":"button_1_single"}'
zigbee2mqtt:info  2020-01-27 22:59:28: MQTT publish: topic 'zigbee2mqtt/0x04cf8cdf3c75b85a', payload '{"linkquality":65,"battery":"100.00","voltage":3000,"action":"button_1_single"}'
zigbee2mqtt:info  2020-01-27 23:00:23: MQTT publish: topic 'zigbee2mqtt/0x04cf8cdf3c75b85a', payload '{"linkquality":63,"battery":"100.00","voltage":3000}'
zigbee2mqtt:info  2020-01-27 23:03:19: MQTT publish: topic 'zigbee2mqtt/0x04cf8cdf3c75b85a', payload '{"linkquality":44,"battery":"100.00","voltage":3000,"action":"button_1_single"}'
zigbee2mqtt:info  2020-01-27 23:03:21: MQTT publish: topic 'zigbee2mqtt/0x04cf8cdf3c75b85a', payload '{"linkquality":39,"battery":"100.00","voltage":3000,"action":"button_2_single"}'
zigbee2mqtt:info  2020-01-27 23:03:22: MQTT publish: topic 'zigbee2mqtt/0x04cf8cdf3c75b85a', payload '{"linkquality":47,"battery":"100.00","voltage":3000,"action":"button_2_single"}'
zigbee2mqtt:info  2020-01-27 23:03:23: MQTT publish: topic 'zigbee2mqtt/0x04cf8cdf3c75b85a', payload '{"linkquality":39,"battery":"100.00","voltage":3000,"action":"button_3_single"}'
zigbee2mqtt:info  2020-01-27 23:03:24: MQTT publish: topic 'zigbee2mqtt/0x04cf8cdf3c75b85a', payload '{"linkquality":36,"battery":"100.00","voltage":3000,"action":"button_3_hold"}'
zigbee2mqtt:info  2020-01-27 23:03:26: MQTT publish: topic 'zigbee2mqtt/0x04cf8cdf3c75b85a', payload '{"linkquality":39,"battery":"100.00","voltage":3000,"action":"button_3_release","duration":1779}'
zigbee2mqtt:info  2020-01-27 23:03:27: MQTT publish: topic 'zigbee2mqtt/0x04cf8cdf3c75b85a', payload '{"linkquality":0,"battery":"100.00","voltage":3000,"action":"button_4_single"}'
zigbee2mqtt:info  2020-01-27 23:03:30: MQTT publish: topic 'zigbee2mqtt/0x04cf8cdf3c75b85a', payload '{"linkquality":0,"battery":"100.00","voltage":3000,"action":"button_4_hold"}'
zigbee2mqtt:info  2020-01-27 23:03:32: MQTT publish: topic 'zigbee2mqtt/0x04cf8cdf3c75b85a', payload '{"linkquality":0,"battery":"100.00","voltage":3000,"action":"button_4_release","duration":2257}'
zigbee2mqtt:info  2020-01-27 23:03:35: MQTT publish: topic 'zigbee2mqtt/0x04cf8cdf3c75b85a', payload '{"linkquality":15,"battery":"100.00","voltage":3000,"action":"button_5_single"}'
zigbee2mqtt:info  2020-01-27 23:03:36: MQTT publish: topic 'zigbee2mqtt/0x04cf8cdf3c75b85a', payload '{"linkquality":15,"battery":"100.00","voltage":3000,"action":"button_5_single"}'
zigbee2mqtt:info  2020-01-27 23:03:39: MQTT publish: topic 'zigbee2mqtt/0x04cf8cdf3c75b85a', payload '{"linkquality":34,"battery":"100.00","voltage":3000,"action":"button_5_hold"}'
zigbee2mqtt:info  2020-01-27 23:03:43: MQTT publish: topic 'zigbee2mqtt/0x04cf8cdf3c75b85a', payload '{"linkquality":15,"battery":"100.00","voltage":3000,"action":"button_5_release","duration":3397}'
zigbee2mqtt:info  2020-01-27 23:03:45: MQTT publish: topic 'zigbee2mqtt/0x04cf8cdf3c75b85a', payload '{"linkquality":31,"battery":"100.00","voltage":3000,"action":"button_6_single"}'
zigbee2mqtt:info  2020-01-27 23:03:47: MQTT publish: topic 'zigbee2mqtt/0x04cf8cdf3c75b85a', payload '{"linkquality":34,"battery":"100.00","voltage":3000,"action":"button_6_single"}'
zigbee2mqtt:info  2020-01-27 23:03:53: MQTT publish: topic 'zigbee2mqtt/0x04cf8cdf3c75b85a', payload '{"linkquality":68,"battery":"100.00","voltage":3000,"action":"button_5_release","duration":13855}'
```

**Comment by jacekpaszkowski** [comment]
Anybody have idea why it behaves this way?

**Comment by jacekpaszkowski** [comment]
Some debug logs:

Not working double click (message in debug is different from "real" single click but is reported as single)
```
zigbee2mqtt:debug 2020-01-30 07:46:03: Received Zigbee message from 'Aqara Opple switch', type 'commandStepColorTemp', cluster 'lightingColorCtrl', data '{"stepmode":1,"stepsize":69,"transtime":7,"minimum":0,"maximum":0}' from endpoint 1 with groupID 0
zigbee2mqtt:info  2020-01-30 07:46:03: MQTT publish: topic 'zigbee2mqtt/Aqara Opple switch', payload '{"linkquality":49,"battery":"100.00","voltage":3000,"action":"button_5_single"}'
```

working single click
```
zigbee2mqtt:debug 2020-01-30 07:46:08: Received Zigbee message from 'Aqara Opple switch', type 'commandStep', cluster 'genLevelCtrl', data '{"stepmode":0,"stepsize":85,"transtime":7}' from endpoint 1 with groupID 0
zigbee2mqtt:info  2020-01-30 07:46:08: MQTT publish: topic 'zigbee2mqtt/Aqara Opple switch', payload '{"linkquality":70,"battery":"100.00","voltage":3000,"action":"button_4_single"}'
```

working hold of button 4
```
zigbee2mqtt:debug 2020-01-30 07:49:04: Received Zigbee message from 'Aqara Opple switch', type 'commandMove', cluster 'genLevelCtrl', data '{"movemode":0,"rate":15}' from endpoint 1 with groupID 0
zigbee2mqtt:info  2020-01-30 07:49:04: MQTT publish: topic 'zigbee2mqtt/Aqara Opple switch', payload '{"linkquality":52,"battery":"100.00","voltage":3000,"action":"button_4_hold"}'
zigbee2mqtt:debug 2020-01-30 07:49:08: Received Zigbee message from 'Aqara Opple switch', type 'commandStop', cluster 'genLevelCtrl', data '{}' from endpoint 1 with groupID 0
zigbee2mqtt:info  2020-01-30 07:49:08: MQTT publish: topic 'zigbee2mqtt/Aqara Opple switch', payload '{"linkquality":70,"battery":"100.00","voltage":3000,"action":"button_4_release","duration":3471}'
```

not working hold on button 1,2 (just single click - device issiue ?!)
```
zigbee2mqtt:debug 2020-01-30 07:47:06: Received Zigbee message from 'Aqara Opple switch', type 'commandOn', cluster 'genOnOff', data '{}' from endpoint 1 with groupID 0
zigbee2mqtt:info  2020-01-30 07:47:06: MQTT publish: topic 'zigbee2mqtt/Aqara Opple switch', payload '{"linkquality":55,"battery":"100.00","voltage":3000,"action":"button_2_single"}'
zigbee2mqtt:debug 2020-01-30 07:47:12: Received Zigbee message from 'Aqara Opple switch', type 'commandStep', cluster 'genLevelCtrl', data '{"stepmode":1,"stepsize":85,"transtime":7}' from endpoint 1 with groupID 0
zigbee2mqtt:info  2020-01-30 07:47:13: MQTT publish: topic 'zigbee2mqtt/Aqara Opple switch', payload '{"linkquality":55,"battery":"100.00","voltage":3000,"action":"button_3_single"}'
zigbee2mqtt:debug 2020-01-30 07:47:15: Received Zigbee message from 'Aqara Opple switch', type 'commandOff', cluster 'genOnOff', data '{}' from endpoint 1 with groupID 0
zigbee2mqtt:info  2020-01-30 07:47:15: MQTT publish: topic 'zigbee2mqtt/Aqara Opple switch', payload '{"linkquality":44,"battery":"100.00","voltage":3000,"action":"button_1_single"}'
```

anothe strange thing is when i perform several operations in a row with the same button. then when i hold the button only "button_x_hold" action is reported and "button_x_release" is missing. I have to perform any action on the other button and then again hold previos one

**Comment by zsiebe** [comment]
I'm experiencing a similar problem but with the aqara opple WXCJKG12LM (4 button) switch. All buttons perform single click, Button 3 and 4 can also do double click, and none can do long press. This behavior is seen in zigbee2mqtt as well as zigbee2mqtt-edge. Hoping to receive some guidance on what to try.

**Comment by jacekpaszkowski** [comment]
So it seems that isn't faulty device. As @zsiebe said please tell what we can do to find the issue :)

**Comment by zsiebe** [comment]
It seems to me that the opple sends zigbee messages that are different for the different buttons. Here is what happens when I press button 1 once, button 2 once, button 1 double, button 2 double and then 3 once, 4 once, 3 double, 4 double

`zigbee2mqtt:debug 2020-02-03 20:15:07: Received Zigbee message from '0x04cf8cdf3c77c4e3', type 'commandOff', cluster 'genOnOff', data '{}' from endpoint 1 with groupID 0
zigbee2mqtt:info  2020-02-03 20:15:07: MQTT publish: topic 'zigbee2mqtt/0x04cf8cdf3c77c4e3', payload '{"battery":"100.00","voltage":3100,"linkquality":84,"action":"button_1_single"}'
zigbee2mqtt:info  2020-02-03 20:15:07: MQTT publish: topic 'zigbee2mqtt/0x04cf8cdf3c77c4e3', payload '{"battery":"100.00","voltage":3100,"linkquality":84,"action":""}'
zigbee2mqtt:debug 2020-02-03 20:15:13: Received Zigbee message from '0x04cf8cdf3c77c4e3', type 'commandOn', cluster 'genOnOff', data '{}' from endpoint 1 with groupID 0
zigbee2mqtt:info  2020-02-03 20:15:13: MQTT publish: topic 'zigbee2mqtt/0x04cf8cdf3c77c4e3', payload '{"battery":"100.00","voltage":3100,"linkquality":84,"action":"button_2_single"}'
zigbee2mqtt:info  2020-02-03 20:15:13: MQTT publish: topic 'zigbee2mqtt/0x04cf8cdf3c77c4e3', payload '{"battery":"100.00","voltage":3100,"linkquality":84,"action":""}'
zigbee2mqtt:debug 2020-02-03 20:15:18: Received Zigbee message from '0x04cf8cdf3c77c4e3', type 'commandOff', cluster 'genOnOff', data '{}' from endpoint 1 with groupID 0
zigbee2mqtt:info  2020-02-03 20:15:18: MQTT publish: topic 'zigbee2mqtt/0x04cf8cdf3c77c4e3', payload '{"battery":"100.00","voltage":3100,"linkquality":63,"action":"button_1_single"}'
zigbee2mqtt:info  2020-02-03 20:15:18: MQTT publish: topic 'zigbee2mqtt/0x04cf8cdf3c77c4e3', payload '{"battery":"100.00","voltage":3100,"linkquality":63,"action":""}'
zigbee2mqtt:debug 2020-02-03 20:15:25: Received Zigbee message from '0x04cf8cdf3c77c4e3', type 'commandOn', cluster 'genOnOff', data '{}' from endpoint 1 with groupID 0
zigbee2mqtt:info  2020-02-03 20:15:25: MQTT publish: topic 'zigbee2mqtt/0x04cf8cdf3c77c4e3', payload '{"battery":"100.00","voltage":3100,"linkquality":78,"action":"button_2_single"}'
zigbee2mqtt:info  2020-02-03 20:15:25: MQTT publish: topic 'zigbee2mqtt/0x04cf8cdf3c77c4e3', payload '{"battery":"100.00","voltage":3100,"linkquality":78,"action":""}'
zigbee2mqtt:debug 2020-02-03 20:15:28: Received Zigbee message from '0x04cf8cdf3c77c4e3', type 'commandStep', cluster 'genLevelCtrl', data '{"stepmode":1,"stepsize":85,"transtime":7}' from endpoint 1 with groupID 0
zigbee2mqtt:info  2020-02-03 20:15:28: MQTT publish: topic 'zigbee2mqtt/0x04cf8cdf3c77c4e3', payload '{"battery":"100.00","voltage":3100,"linkquality":68,"action":"button_3_single"}'
zigbee2mqtt:info  2020-02-03 20:15:28: MQTT publish: topic 'zigbee2mqtt/0x04cf8cdf3c77c4e3', payload '{"battery":"100.00","voltage":3100,"linkquality":68,"action":""}'
zigbee2mqtt:debug 2020-02-03 20:15:35: Received Zigbee message from '0x04cf8cdf3c77c4e3', type 'commandStep', cluster 'genLevelCtrl', data '{"stepmode":0,"stepsize":85,"transtime":7}' from endpoint 1 with groupID 0
zigbee2mqtt:info  2020-02-03 20:15:35: MQTT publish: topic 'zigbee2mqtt/0x04cf8cdf3c77c4e3', payload '{"battery":"100.00","voltage":3100,"linkquality":89,"action":"button_4_single"}'
zigbee2mqtt:info  2020-02-03 20:15:35: MQTT publish: topic 'zigbee2mqtt/0x04cf8cdf3c77c4e3', payload '{"battery":"100.00","voltage":3100,"linkquality":89,"action":""}'
zigbee2mqtt:debug 2020-02-03 20:15:42: Saving state to file /share/zigbee2mqtt/state.json
zigbee2mqtt:debug 2020-02-03 20:15:44: Received Zigbee message from '0x04cf8cdf3c77c4e3', type 'commandStepColorTemp', cluster 'lightingColorCtrl', data '{"stepmode":1,"stepsize":69,"transtime":7,"minimum":0,"maximum":0}' from endpoint 1 with groupID 0
zigbee2mqtt:info  2020-02-03 20:15:44: MQTT publish: topic 'zigbee2mqtt/0x04cf8cdf3c77c4e3', payload '{"battery":"100.00","voltage":3100,"linkquality":84,"action":"button_3_double"}'
zigbee2mqtt:info  2020-02-03 20:15:44: MQTT publish: topic 'zigbee2mqtt/0x04cf8cdf3c77c4e3', payload '{"battery":"100.00","voltage":3100,"linkquality":84,"action":""}'
zigbee2mqtt:debug 2020-02-03 20:15:50: Received Zigbee message from '0x04cf8cdf3c77c4e3', type 'commandStepColorTemp', cluster 'lightingColorCtrl', data '{"stepmode":3,"stepsize":69,"transtime":7,"minimum":0,"maximum":0}' from endpoint 1 with groupID 0
zigbee2mqtt:info  2020-02-03 20:15:50: MQTT publish: topic 'zigbee2mqtt/0x04cf8cdf3c77c4e3', payload '{"battery":"100.00","voltage":3100,"linkquality":73,"action":"button_4_double"}'
zigbee2mqtt:info  2020-02-03 20:15:50: MQTT publish: topic 'zigbee2mqtt/0x04cf8cdf3c77c4e3', payload '{"battery":"100.00","voltage":3100,"linkquality":73,"action":""}'`

As you can see for button 1 and 2 it sends command_on type messages whereas 3 and 4 send Commandstep and commandStepColorTemp messages for single and double respectively.

It seems to me that the device due to its firmware might not be capable of sending double button presses on button 1 and 2. Is there something I am missing? Maybe there would be a way to install custom firmware on the device?

**Comment by danielwelch** [comment]
Looks like this discussion belongs in the zigbee2mqtt issue tracker. I'll close it here. Feel free to continue the discussion, but you may be better served opening an issue over in the zigbee2mqtt repository.
