### ISSUE TITLE
Clarification about configuration, with examples

### ISSUE THREAD

**Issue by dunxd** [danielwelch/hassio-zigbee2mqtt#350]
I am relatively new to HASSIO and ZigBee.  I don't understand the documentation on requirements for configuring hassio-zigbee2mqtt, and feel that the documentation could be a little clearer for newbies.  I find the following confusing:

> Hass.io requires add-on configuration in JSON format, rather than YAML. If you don't understand the difference, you can use a YAML-to-JSON converter.

The configuration examples given, and the configuration for the zigbee2mqtt add-on are in YAML format not JSON, so this paragraph seems to say something different to what I see.  Why is that?

> If you are using groups or device-specific settings, you must use seperate files, and provide the paths to these files in their corresponding config options as described by the zigbee2mqtt docs. This is due to a limitation Hass.io places on nested config levels.

Does this mean that I **must** use a Groups.yaml file if I want to set up groups?  Or can I define my groups in the configuration page for zigbee2mqtt?

If I must use a groups.yaml file, where do I create this file using the Home Assistant UI? Or do I need to manually create/edit a file elsewhere in the filesystem?  I am assuming I should edit groups.yaml in /root/share/zigbee2mqtt, however here I am further confused, because when I open groups.yaml in nano, I see {} suggesting that this file should be JSON, but it uses .yaml in the filename.

If the documentation spelled out that if you want to use groups you need to edit groups.yaml in /root/share/zigbee2mqtt and then provide a short example of a group config, that would be very clear.  If the groups config file should be in JSON, then naming it groups.json would be a lot clearer than groups.yaml.

**Comment by Jarpetnee** [comment]
Agreed @dunxd. I also find the documentation for this very confusing...

**Comment by danielwelch** [comment]
@dunxd Hey, sorry for the huge delay. I'm going back through some old issues and trying to clean up.

Thanks for bringing up the concerns. You're right, the documentation could definitely be improved in a number of areas. I think the best case scenario, big picture, would just be to roll the add-on docs into the current docs on zigbee2mqtt.io, with a setup guide and some dedicated pages for specific steps or FAQs.

To address your specific concerns, though:

>The configuration examples given, and the configuration for the zigbee2mqtt add-on are in YAML format not JSON, so this paragraph seems to say something different to what I see. Why is that?

Not really. The configuration for the *add-on* has to be JSON. When you are configuring your add-on via the Home Assistant front-end interface, you are entering JSON. The configuration for zigbee2mqtt (and therefore the examples in zigbee2mqtt documentation) are in YAML. A part of what this add-on does is just take the JSON configuration you provide and give it to zigbee2mqtt as YAML it expects. If you're referring to the config examples on the README for this add-on, those examples show configuration entries for Home Assistant itself (not an add-on) and for the Lovelace front-end.

Why do you have to configure add-ons with JSON, when nearly everything else in Home Assistant is configured via YAML? Good question!

>Does this mean that I must use a Groups.yaml file if I want to set up groups? Or can I define my groups in the configuration page for zigbee2mqtt?

Yes, hence the word must. If you want to use that group functionality, you must use a separate file. This is because of restrictions on configuration nesting inherent in how Home Assistant parses your add-on configuration. The file should be saved in your data path. 

>  I am assuming I should edit groups.yaml in /root/share/zigbee2mqtt, however here I am further confused, because when I open groups.yaml in nano, I see {} suggesting that this file should be JSON, but it uses .yaml in the filename.

If you indicated that this should be used by zigbee2mqtt, it's possible that the file was modified by zigbee2mqtt while running (although I'm not too familiar with the details of how the library handles `groups.yaml`. If it makes you feel better, JSON is valid YAML. 

Hope this helps!

**Comment by ciotlosm** [comment]
Closing this as questions were answered. Also I'm working to clean and improve documentation. Also contributions are welcome. The more people helping with docs, the clear would be for more people 😄
