### ISSUE TITLE
docker hub image requires tag to match config.json version

### ISSUE THREAD

**Issue by ciotlosm** [danielwelch/hassio-zigbee2mqtt#4]
https://hub.docker.com/r/dwelch2101/zigbee2mqtt-armhf/tags/ currently is not tagged, and the version inside config.json is 'dev'. 

Version needs to be a number, and that number must also be a tag in docker hub. 

Sample error:
```
18-05-10 19:23:29 INFO (MainThread) [hassio.addons.git] Clone addon https://github.com/ciotlosm/hassio-zigbee2mqtt repository
18-05-10 19:23:33 INFO (MainThread) [hassio.addons] Load addons: 36 all - 1 new - 0 remove
18-05-10 19:23:49 INFO (MainThread) [hassio.addons.addon] Create Home-Assistant addon data folder /data/addons/data/69f3b574_zigbee2mqtt
18-05-10 19:23:49 INFO (SyncWorker_0) [hassio.docker.interface] Pull image dwelch2101/zigbee2mqtt-armhf tag dev.
18-05-10 19:23:52 ERROR (SyncWorker_0) [hassio.docker.interface] Can't install dwelch2101/zigbee2mqtt-armhf:dev -> 404 Client Error: Not Found ("manifest for dwelch2101/zigbee2mqtt-armhf:dev not found").
```

**Comment by danielwelch** [comment]
I use https://github.com/hassio-addons/build-env for managing docker builds and tags. I have not successfully run this yet, which is why it's currently not tagged. Once we have a working build, and with the setup I have, all commits to the `master` branch will be built and tagged on Docker with `test`. All git tags will be built with the `latest` tag and also tagged with the git tag (which I use a semver number for). I wouldn't worry about this yet; I'd test locally. When ready for a preliminary release, we can tag a docker build `0.1`. See the build-env repo linked above and the `distribute.sh` script in this repo to learn more, feel free to ask me any questions.

**Comment by ciotlosm** [comment]
Super!

**Comment by danielwelch** [comment]
Yep, it looks like there’s several problems with this step that need to be solved. Going off of the material you linked in the original repo, it looks like this build needs additional dependencies that I haven’t included. I also ran into a problem with installing gyp that needs to be debugged. Hoping to push changes tonight.

**Comment by danielwelch** [comment]
After some changes, the Docker images are now building on [travis](https://travis-ci.org/danielwelch/hassio-zigbee2mqtt/builds/377501559) so should be able to build locally as well. Closing this issue.
