### ISSUE TITLE
Auto-detect type of adapter (ex. conbee)

### ISSUE THREAD

**Issue by ciotlosm** [danielwelch/hassio-zigbee2mqtt#424]
Use https://developers.home-assistant.io/docs/add-ons/communication#supervisor-api to get serial information and build some type of matching to auto-detect type of adapters.

This would facilitate automatically setting the adapter type for some sticks. See: https://www.zigbee2mqtt.io/information/supported_adapters.html#conbee-ii

**Comment by scootec** [comment]
I had this working in my DIY add-on but have removed it temporarily thinking that it is functionality that probably should exist within Zigbee2MQTT (with the `adapter: null` option).
Check it out here:
[Here is the relevant line in the config script.](https://github.com/scootec/addon-zigbee2mqtt/blob/adfabbd68578bddc293494dc9556edb67d5eb48b/zigbee2mqtt/rootfs/etc/cont-init.d/zigbee2mqtt.sh#L26)

**Comment by ciotlosm** [comment]
@scootec i've had a look at your repo, and it seems you are using some more advanced concepts for the init scripts and parts of build. Are you not interested to get some of those concepts merged in this repo?

**Comment by scootec** [comment]
> @scootec i've had a look at your repo, and it seems you are using some more advanced concepts for the init scripts and parts of build. Are you not interested to get some of those concepts merged in this repo?

@ciotlosm I would be keen to get them merged here. I initially created my version just to learn more about how addons worked, but ended up keeping it rolling since I liked having my config saved in the `/config` directory with home assistant and other community addons.

I had planned on adding options to the addon options that would enable herdsman debugging, and other things you cannot achieve by options in `configuration.yaml`, but have not gotten around to that yet...

> I recently started to work on the add-on again and added bits and pieces of bashio for things like automatic mqtt credentials

That's great! I can submit a pull request for the auto adapter configuration. I just need some examples of each adapter types `/dev/serial/by-id/` path so we can pattern match that to identify the adapter. I only have a conbee 2 stick that shows up as ` /dev/serial/by-id/usb-dresden_elektronik_ingenieurtechnik_GmbH_ConBee_II_DE1963506-if00`, so I assume we can identify other sticks in a similar fashion.

**Comment by ciotlosm** [comment]
@scootec make sure you use the `dev` branch for your PR. I am going to release the dev branch soon, but I think besides the adapter, a migration to proper s6 services is needed. In my mind next steps would be:
- Release current dev changes
- Migrate from run.sh to s6 services and startup scripts
- Drop the socat.sh hack (calling itself with a background run) and use a proper service
- Add the adapter support
- Look at moving config /config if it's a more accepted setup - but keep the backup functionality
  - To be honest, current backup method sucks - I'd be more inclined to de a backup if the add-on & z2m started successfully

**Comment by scootec** [comment]
@ciotlosm sounds good to me.
Once you merge the changes to the dev branch I will jump in and see what I can do 👍

**Comment by ciotlosm** [comment]
@scootec I've started the work with pipeline builds and all here for now: https://github.com/zigbee2mqtt/hassio-zigbee2mqtt 
You can have a look there, and start a PR against `dev` branch. I'm still getting fixes in as local development is slow, but it's closer to the final form now.
