### ISSUE TITLE
LQI slowly goes up to 255, then drops to 0 and climbs again...bug?

### ISSUE THREAD

**Issue by s3frank** [danielwelch/hassio-zigbee2mqtt#440]
Hi there,
I am running Conbee II on RPI4. I have Debian 10 installed, Docker and run Homeassistant (0.116.2) in containers on it. I have installed the official hassio addon for zigbee2mqtt and i am absolutely loving it. You have done amazing work and packaged it so well, thank you for that. My network is stable and automations in NodeRed work super smooth and fast.

But my LQI data seems to not reflect that reality at all. In fact I think something is going wrong in the code around endpoint availability checking. I have configured my zigbee2mqtt addon version: 1.15.0 with:
advanced:
  availability_timeout: 120

My LQI across all devices appears to be looping. It starts with a number say 35 across most devices no matter how far or close they are. And then slowly they all climb up to 255 and then drop to 0. And then it starts again slowly to 255.
I think it has something to do with the availability check that is turned on by the 2 minute timeout routine I have activated.

Here are some screenshots for you to further show what is happening.
![image](https://user-images.githubusercontent.com/2191242/95566798-a499b700-0a54-11eb-9e70-f3d5ba945248.png)

![image](https://user-images.githubusercontent.com/2191242/95566965-e0cd1780-0a54-11eb-8fff-8159324ca9ac.png)

**Comment by ciotlosm** [comment]
That is not a problem with the add-on, however the behaviour you are showing is what you get usually when you're graphing a "counter". The drop is usually when the counter reaches max and starts from min again.

I'm using 1.15.0 and LQI is ok on my setup, so my best guess is that for Conbee the metric is not exposed correctly. 

As this is certainly not a problem with the add-on, I would recommend you open an issue here: https://github.com/Koenkk/zigbee2mqtt/issues or add comments about your problem here: https://github.com/Koenkk/zigbee-herdsman/issues/72

**Comment by s3frank** [comment]
Alright thanks. I have opened a new issue with zigbee2mqtt. I agree it looks like that is a problem on that part as Home Assistant is really just the client / viewer of the data that it receives via mqtt. For completeness here is the issue link:
https://github.com/Koenkk/zigbee2mqtt/issues/4630
