### ISSUE TITLE
Repostitory structure for v1.15.0 is not compliant

### ISSUE THREAD

**Issue by Toinieboy** [danielwelch/hassio-zigbee2mqtt#445]
Am i at a too high version? Running  0.116.2

**Comment by ciotlosm** [comment]
You are making confusions between component versions. If you are running home assistant you will have (stable versions):
- Home Assistant Core: which is `0.116.2` at the time of this writing
- Home Assistant Supervisor: which is `247` at the time of this writing
- Home Assistant OS: which is `4.14`  at the time of this writing

On top of the above you will have add-ons which are supported and managed by the Supervisor. In this particular case `hassio-zigbee2mqtt`. 

Current stable version for the add-on (in the official repo) is `1.15.0` which inside has Zigbee2mqtt Core which is also `1.15.0`. As stated in the documentation, if we release a new version of the add-on that doesn't upgrade Zigbee2mqtt Core, we just add a number at the end. Example: 1.15.0.1, 1.15.0.2, etc. 

Please note that we're moving soon the add-on to a different repository / organisation and updating the versioning to use a - instead of . to separate Z2m Core from the add-on. 

I'm not sure what you want to achieve, but you're looking at the wrong component for version. If you don't see the add-on by default in your Add-ons please see the installation instructions. As this add-on is not part of Core Add-ons or Community Add-ons, it will require that you manually at the repository source.

**Comment by Toinieboy** [comment]
Hi Ciotlosm,

this is the error i'm receiving when i want to add the custom repository.

Kind regards
Toine
