### ISSUE TITLE
zigbee2mqtt addon needs restart every minute

### ISSUE THREAD

**Issue by bart1604** [danielwelch/hassio-zigbee2mqtt#46]
Hi guys,

First of all a shout out to everybody who is/was involved with this project, i think it has great potential.

I have connected 3 tradfri spots, it works fine for a minute or so but then nothing works anymore. I have to restart the zigbee2mqtt addon within my hassio.

Does anyone else have this issue? The logs within the addon says the following:

zigbee2mqtt:error 2018-8-26 20:53:01 Zigbee publish to 'xxxxxxxxxxxxx', genOnOff - off - {} - null failed with error Error: request timeout
  zigbee2mqtt:error 2018-8-26 20:53:04 Zigbee publish to 'xxxxxxxxxxxxxx', genOnOff - off - {} - null failed with error Error: request timeout
  zigbee2mqtt:error 2018-8-26 20:53:07 Zigbee publish to 'xxxxxxxxxxxxxxxx', genOnOff - off - {} - null failed with error Error: request timeout

After restarting the zigbee2mqtt addon i can turn the lights on and off for a minute but then again these errors

Thanks for your time!

Greetings

**Comment by bart1604** [comment]
I think i found it but I'm not sure how to fix it. I see that the timestamp of my log entries are exactly 2 hours behind. The time of the host is correct, so only within the zigbee2mqtt addon (docker container) the time is off. Can anyone help me to set the correct time within the docker container?

**Comment by danielwelch** [comment]
I kind of doubt that’s the reason you’re having this error. I also think it’s more likely that this is an issue with the library itself rather than the add-on, have you raised an issue / looked through issues over there?

Out of curiosity, is your local time 2 hours offset from UTC time?

I’ll leave this issue open in case it really is a problem with the add-on

**Comment by danielwelch** [comment]
By library, I mean zigbee2mqtt itself. This add on just makes zigbee2mqqtt available as a Hass.io add-on. It’s basically just instructions for Hass.io to build/run zigbee2mqtt and exposes a configuration interface via the Hass.io UI. Things can go wrong in that process, and those issues should be filed here. I think your issue is more likely a problem with zigbee2mqtt itself as it seems that the add-on starts up ok

**Comment by bart1604** [comment]
Hi Daniel,

I'm closing this issue. Thank you for your help.

I've done 2 more tests. I've put in a clean HDD in my Intel NUC and installed Ubuntu directly to it, not in a VM. Then I installed zigbee2mqtt and everything works fine.

So it looks like the ESX virtualisation software is causing the problems.
