### ISSUE TITLE
custom encryption key doesn't work

### ISSUE THREAD

**Issue by Claypaenguin** [danielwelch/hassio-zigbee2mqtt#88]
When I try to add an encryption key to the _configuration.yaml_ as described in the [zigbee2mqtt documentation](https://koenkk.github.io/zigbee2mqtt/how_tos/how_to_secure_network.html) the formatting changes to this after restarting the addon:
```
advanced:
  network_key:
  - 13
  - 7
  - 2
  - 7
  - 9
  - 15
  - 5
  - 7
  - 2
  - 10
  - 3
  - 2
  - 7
  - 8
  - 1
  - 4
```
and my old devices still stay connected and don't need repairing. I'm assuming that means that the encryption key wasn't applied.

**Comment by danielwelch** [comment]
The formatting change occurs because the file is read into a python object, and then is re-written in a format determined by PyYAML. It seems like PyYAML is using the normal, expected syntax, whereas the zigbee2mqtt docs use the flow collections version. I don’t see a reason why one would work and the other wouldn’t. @Koenkk any insight re: applying the encryption key?

**Comment by Koenkk** [comment]
The encryption key documentation shouldn't be in the master branch (my bad) as it is only supported in the dev branch yet.

That means when using the hassio `-edge` version it should work.

**Comment by danielwelch** [comment]
Looks like this is now supported in v1.1.0. I've just updated the add-on and images are being built now, so I'll close this.
