### ISSUE TITLE
configuration.yaml gets overwritten on addon restart

### ISSUE THREAD

**Issue by quantummobile** [danielwelch/hassio-zigbee2mqtt#90]
Hello,

Is there a simple way to edit zigbee2mqtt configuration.yaml file directly and keep the changes? I've tried with no success, as configuration.yaml gets overwritten with default values from zigbee2mqtt addon's frontend on addon restart.

Thank you in advance.

**Comment by danielwelch** [comment]
Those instructions were written when there were other settings not yet exposed through the add-on config, and the intended behavior is still that only those config settings explicitly defined in the front-end will overwrite the edited YAML. You raise a good point that all of this kind of clouds the picture though. I’ll consider an option to prevent overwriting.

**Comment by quantummobile** [comment]
Hi Daniel,

would be really great to have an option to prevent overwriting.

Many thanks in advance.

**Comment by quantummobile** [comment]
Hi Daniel,

until we have that option - please give an example of code how to add device specific configuration in the front end.

Thanks in advance.

**Comment by danielwelch** [comment]
I've added the `overwrite` option to both the edge version and the latest stable release (v1.1.0), which is being built now. Set to `false` to disable overwriting. Docs also updated to show how to use device-specific configuration. Thanks!

**Comment by quantummobile** [comment]
Well done, many thanks!

**Comment by ekaats** [comment]
This issue still occurs for me, at least using a coordinator on the zigbee 3.0 firmware. When reflashing to 1.2, everything works as expected. Could there be a setting specific to 3.0 that forces the configuration to be reset?

The overwrite flag does not make a difference in this case, as is editing the .bk file that is used to backup the configuration file.

For me the issue is not urgent as long as 1.2 works, but I thought I'd chime in anyway.

**Comment by danielwelch** [comment]
If you’re on 1.5 or higher, the `overwrite` feature was removed, as the way the add-on passes configuration to zigbee2mqtt was entirely changed.

**Comment by jbrechtel** [comment]
Hey @danielwelch, I'm running into this. My use case is somewhat quirky, I suppose, so it probably doesn't make sense as a feature request...I'm more curious if there's anything I can do (hacky or not) to allow myself to manage the config outside of the frontend.

What I'd *like* to be able to do is manage my config files in a git repository and restart the appropriate service when they're changed.

This is convenient for me because it allows me to edit the files in my preferred editor and gives me versioning over the files themselves.

I've tried stopping the service and editing the "yaml" file then starting it but that has no effect either.

Does the addon's persisted/authoritative YAML configuration exist on disk anywhere? Is that entirely opaque to the addon itself? I'd be willing to jump through some hoops to update it but I'm not sure where to start looking.

**Comment by danielwelch** [comment]
Happy to try and help. The problem with this add-ons approach for your use case is that this docker container’s run script reads the front-end configuration and writes it each time it starts (check the run script out for yourself). The run script also sets where zigbee2mqtt will look for that configuration as it invokes zigbee2mqtt to start. You could fairly easily fork this add-on and modify the run script to do whatever you want with the add-on configuration (including nothing at all), and just rely on a file that you have saved to disk and is mapped into the container (see the add-on config to see which directories are mounted into the container). Just make sure your file location corresponds with the file the run script provides to zigbee2mqtt, or modify the run script accordingly.

**Comment by ewoutdenheijer** [comment]
Hi, Zigbee2mqtt now has a pretty nice build in web interface. It's also possible to change settings. These changes are overwritten by a restart. This is a pity, because the settings in the web interface are actually more comprehensive then what's being passed trough by the add on.

Perhaps it's worth considering to rely on the native web interface for configuration from now on. That way you don't have to keep track of configuration options in de add on. Alternatively, you could perhaps make this in itself an option?

**Comment by ciotlosm** [comment]
There is an issue raised where we'll try to cover all implications: https://github.com/zigbee2mqtt/hassio-zigbee2mqtt/issues/41

**Comment by mremedi2023** [comment]
Hi, I have some devices that flood the data bus, so the documentation suggests adding a line to the configuration.yaml. Ex:

Stop message flooding
This unit has a bug that makes it send multiple messages when updating. To stop this from flooding your MQTT Queues, please add the following to your configuration.yaml file:

devices:
'0x12345678':
friendly_name: thermostat
debounce: 1

As discussed in this thread, it doesn't matter if I add the line to the file, when I reboot the line is no longer added, how can I fix this?
